project:
  type: book
  output-dir: docs

book:
  title: "YELLOW SUBMARINE Progress Journal"
  repo-url: https://github.com/pjournal/mef07g-yellowsubmarine
  chapters:
    - index.qmd
    - assignment1.qmd
    - preprocesseddata.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo

