project:
  type: book
  output-dir: docs

book:
  title: "YELLOW SUBMARINE Progress Journal"
  repo-url: https://github.com/pjournal/mef07g-yellowsubmarine
  chapters:
    - index.qmd
    - preprocesseddata.qmd
    - exploratorydataanalysis.qmd
    - finalreport.qmd
    - assignment1.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: journal
  pdf:
    documentclass: scrreprt
    chapters:
      preprocesseddata.qmd: false
      exploratorydataanalysis.qmd: false
      finalreport.qmd: true 
      index.qmd: false
      assignment1.qmd: false

