# Introduction {.unnumbered}

<!--
::: {.callout-caution title="Setup To-Do"}

Here is the list of items to properly set this Progress Journal up.

1. Replace the name placeholder "YELLOW SUBMARINE" on `index.qmd` with your name or group name.
2. Replace the name placeholder "YELLOW SUBMARINE" on `_quarto.yml` with your name or group name.
3. Replace the repository link `https://github.com/pjournal/mef07g-yellowsubmarine` with your or your group's repository link.
4. If this is a group PJ, follow the instructions in comments on `index.qmd` and add members, group name, project name and project short description.
5. If this repository does not use RStudio/Posit, then you can also remove `.Rproj` file. Otherwise rename it with your repository name (e.g, mefXX-reponame).

Then test with `quarto preview` on Terminal. If everything is ok, execute `quarto render` command in Terminal.

**Finally, delete the above section (including this sentence) and (GitHub) push the changes to your repository.**
::: -->
<!-- DO NOT TOUCH THIS PART EXCEPT FILLING YOUR OR YOUR GROUP's NAME -->

This progress journal covers YELLOW SUBMARINE's work during their term at [BDA 503 Fall 2023](https://mef-bda503.github.io/fall23/).

Each section is an assignment or an individual work.

<!-- IF THIS IS A GROUP UNCOMMENT BELOW -->

::: {style="text-align: center;"}
<iframe width="680" height="430" src="https://www.youtube.com/embed/7osS1YQZPSQ" frameborder="0" allowfullscreen style="display: inline-block;"></iframe>
</iframe>
:::

[*MEF University, Exploratory Data Analytics, Yellow Submarine's Group Project, Teaser, 2023*](https://www.youtube.com/watch?v=7osS1YQZPSQ)


World Integrated Trade Solution (WITS) emerges as a pivotal platform, offering a comprehensive view of international trade dynamics, with a particular focus on Turkey from 2002 to 2020. This powerful tool aggregates data from diverse sources to furnish users with valuable insights into Turkey's merchandise trade, tariffs, and non-tariff measures during this specific period. With an expansive database, WITS facilitates informed decision-making and strategic planning for researchers, policymakers, and businesses interested in Turkey's trade landscape.

Embarking on an Exploratory Data Analysis (EDA) journey within WITS involves loading datasets, cleaning data, and employing statistical and visual analyses specific to Turkey's trade from 2002 to 2020. This process unveils trade patterns, identifies trends, and provides actionable insights, enabling stakeholders to navigate the complexities of Turkey's trade dynamics during this crucial timeframe. The synergy between WITS and EDA empowers users to make informed decisions and strategic choices, fostering a more interconnected and informed landscape for Turkey's economy and trade.

# Group Members

+ [Sezer Türkmen](https://pjournal.github.io/mef07-sezerlucianturkmen/)  
+ [Sezgi Ayhan](https://pjournal.github.io/mef07-sezgia/)

# Group Project Details

Our group project is Turkey Analysis - Trade Balance & Partners. [Turkey-Trade-Analysis] 

We use datasets of World Integrated Trade Solution, a pivotal platform, offering a comprehensive view of international trade dynamics, with a particular focus on Turkey from 2002 to 2020. Main objective of our analysis is to find out actionable insights about Turkey's position in global trade, product categories that Turkey holds strong export position or import dependency, diversification of import sources and export revenue streams. These insights might help making gap analysis on Turkey's trade balance to   suggest a new economy model.


